//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VX.Desktop.ServiceFacade.VocabExtService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResponse", Namespace="http://schemas.datacontract.org/2004/07/VX.Domain")]
    [System.SerializableAttribute()]
    public partial class ServiceOperationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationActionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationActionCode {
            get {
                return this.OperationActionCodeField;
            }
            set {
                if ((this.OperationActionCodeField.Equals(value) != true)) {
                    this.OperationActionCodeField = value;
                    this.RaisePropertyChanged("OperationActionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VocabExtService.IVocabExtService")]
    public interface IVocabExtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTask", ReplyAction="http://tempuri.org/IVocabExtService/GetTaskResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object GetTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTasksAllVocabBanks", ReplyAction="http://tempuri.org/IVocabExtService/GetTasksAllVocabBanksResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object[] GetTasksAllVocabBanks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTasksSpecifiedVocabBanks", ReplyAction="http://tempuri.org/IVocabExtService/GetTasksSpecifiedVocabBanksResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object[] GetTasksSpecifiedVocabBanks(int[] vocabBanksIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetVocabBanksList", ReplyAction="http://tempuri.org/IVocabExtService/GetVocabBanksListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object[] GetVocabBanksList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTranslations", ReplyAction="http://tempuri.org/IVocabExtService/GetTranslationsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object[] GetTranslations(string vocabBankId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetWords", ReplyAction="http://tempuri.org/IVocabExtService/GetWordsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object[] GetWords(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/CreateNewVocabularyBank", ReplyAction="http://tempuri.org/IVocabExtService/CreateNewVocabularyBankResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object CreateNewVocabularyBank();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetLanguages", ReplyAction="http://tempuri.org/IVocabExtService/GetLanguagesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object[] GetLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/DeleteVocabularyBank", ReplyAction="http://tempuri.org/IVocabExtService/DeleteVocabularyBankResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object DeleteVocabularyBank(string vocabBankId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/SaveTranslation", ReplyAction="http://tempuri.org/IVocabExtService/SaveTranslationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object SaveTranslation(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/DetachTranslation", ReplyAction="http://tempuri.org/IVocabExtService/DetachTranslationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object DetachTranslation(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/UpdateBankHeaders", ReplyAction="http://tempuri.org/IVocabExtService/UpdateBankHeadersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object UpdateBankHeaders(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/SaveWord", ReplyAction="http://tempuri.org/IVocabExtService/SaveWordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object SaveWord(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/ValidateWord", ReplyAction="http://tempuri.org/IVocabExtService/ValidateWordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Desktop.ServiceFacade.VocabExtService.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.DataContracts.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        object ValidateWord(System.IO.Stream data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVocabExtServiceChannel : VX.Desktop.ServiceFacade.VocabExtService.IVocabExtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VocabExtServiceClient : System.ServiceModel.ClientBase<VX.Desktop.ServiceFacade.VocabExtService.IVocabExtService>, VX.Desktop.ServiceFacade.VocabExtService.IVocabExtService {
        
        public VocabExtServiceClient() {
        }
        
        public VocabExtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VocabExtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocabExtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocabExtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object GetTask() {
            return base.Channel.GetTask();
        }
        
        public object[] GetTasksAllVocabBanks() {
            return base.Channel.GetTasksAllVocabBanks();
        }
        
        public object[] GetTasksSpecifiedVocabBanks(int[] vocabBanksIds) {
            return base.Channel.GetTasksSpecifiedVocabBanks(vocabBanksIds);
        }
        
        public object[] GetVocabBanksList() {
            return base.Channel.GetVocabBanksList();
        }
        
        public object[] GetTranslations(string vocabBankId) {
            return base.Channel.GetTranslations(vocabBankId);
        }
        
        public object[] GetWords(string searchString) {
            return base.Channel.GetWords(searchString);
        }
        
        public object CreateNewVocabularyBank() {
            return base.Channel.CreateNewVocabularyBank();
        }
        
        public object[] GetLanguages() {
            return base.Channel.GetLanguages();
        }
        
        public object DeleteVocabularyBank(string vocabBankId) {
            return base.Channel.DeleteVocabularyBank(vocabBankId);
        }
        
        public object SaveTranslation(System.IO.Stream data) {
            return base.Channel.SaveTranslation(data);
        }
        
        public object DetachTranslation(System.IO.Stream data) {
            return base.Channel.DetachTranslation(data);
        }
        
        public object UpdateBankHeaders(System.IO.Stream data) {
            return base.Channel.UpdateBankHeaders(data);
        }
        
        public object SaveWord(System.IO.Stream data) {
            return base.Channel.SaveWord(data);
        }
        
        public object ValidateWord(System.IO.Stream data) {
            return base.Channel.ValidateWord(data);
        }
    }
}
