//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VX.Desktop.ServiceFacade.VocabExtService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VocabExtService.IVocabExtService")]
    public interface IVocabExtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTask", ReplyAction="http://tempuri.org/IVocabExtService/GetTaskResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object GetTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTasksAllVocabBanks", ReplyAction="http://tempuri.org/IVocabExtService/GetTasksAllVocabBanksResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object[] GetTasksAllVocabBanks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTasksSpecifiedVocabBanks", ReplyAction="http://tempuri.org/IVocabExtService/GetTasksSpecifiedVocabBanksResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object[] GetTasksSpecifiedVocabBanks(int[] vocabBanksIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetVocabBanksSummary", ReplyAction="http://tempuri.org/IVocabExtService/GetVocabBanksSummaryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object[] GetVocabBanksSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetTranslations", ReplyAction="http://tempuri.org/IVocabExtService/GetTranslationsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object[] GetTranslations(string vocabBankId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetWords", ReplyAction="http://tempuri.org/IVocabExtService/GetWordsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object[] GetWords(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/CreateVocabularyBank", ReplyAction="http://tempuri.org/IVocabExtService/CreateVocabularyBankResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object CreateVocabularyBank();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/GetLanguages", ReplyAction="http://tempuri.org/IVocabExtService/GetLanguagesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object[] GetLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/DeleteVocabularyBank", ReplyAction="http://tempuri.org/IVocabExtService/DeleteVocabularyBankResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object DeleteVocabularyBank(string vocabBankId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/SaveTranslation", ReplyAction="http://tempuri.org/IVocabExtService/SaveTranslationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object SaveTranslation(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/DetachTranslation", ReplyAction="http://tempuri.org/IVocabExtService/DetachTranslationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object DetachTranslation(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/UpdateBankSummary", ReplyAction="http://tempuri.org/IVocabExtService/UpdateBankSummaryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object UpdateBankSummary(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/SaveWord", ReplyAction="http://tempuri.org/IVocabExtService/SaveWordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object SaveWord(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabExtService/ValidateWord", ReplyAction="http://tempuri.org/IVocabExtService/ValidateWordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Responses.Impl.ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.VocabBankContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TranslationContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.WordContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.LanguageContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TagContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Entities.Impl.TaskContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VX.Domain.Surrogates.Impl.VocabBankSummary))]
        object ValidateWord(System.IO.Stream data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVocabExtServiceChannel : VX.Desktop.ServiceFacade.VocabExtService.IVocabExtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VocabExtServiceClient : System.ServiceModel.ClientBase<VX.Desktop.ServiceFacade.VocabExtService.IVocabExtService>, VX.Desktop.ServiceFacade.VocabExtService.IVocabExtService {
        
        public VocabExtServiceClient() {
        }
        
        public VocabExtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VocabExtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocabExtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocabExtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object GetTask() {
            return base.Channel.GetTask();
        }
        
        public object[] GetTasksAllVocabBanks() {
            return base.Channel.GetTasksAllVocabBanks();
        }
        
        public object[] GetTasksSpecifiedVocabBanks(int[] vocabBanksIds) {
            return base.Channel.GetTasksSpecifiedVocabBanks(vocabBanksIds);
        }
        
        public object[] GetVocabBanksSummary() {
            return base.Channel.GetVocabBanksSummary();
        }
        
        public object[] GetTranslations(string vocabBankId) {
            return base.Channel.GetTranslations(vocabBankId);
        }
        
        public object[] GetWords(string searchString) {
            return base.Channel.GetWords(searchString);
        }
        
        public object CreateVocabularyBank() {
            return base.Channel.CreateVocabularyBank();
        }
        
        public object[] GetLanguages() {
            return base.Channel.GetLanguages();
        }
        
        public object DeleteVocabularyBank(string vocabBankId) {
            return base.Channel.DeleteVocabularyBank(vocabBankId);
        }
        
        public object SaveTranslation(System.IO.Stream data) {
            return base.Channel.SaveTranslation(data);
        }
        
        public object DetachTranslation(System.IO.Stream data) {
            return base.Channel.DetachTranslation(data);
        }
        
        public object UpdateBankSummary(System.IO.Stream data) {
            return base.Channel.UpdateBankSummary(data);
        }
        
        public object SaveWord(System.IO.Stream data) {
            return base.Channel.SaveWord(data);
        }
        
        public object ValidateWord(System.IO.Stream data) {
            return base.Channel.ValidateWord(data);
        }
    }
}
